### ISSUE TITLE
Go generate - stringer.exe not found

### ISSUE THREAD

**Issue by jnflint** [Boostport/address#1]
Had an issue with running go generate.
Output:

> Generating code...
> Formatting generated code...
> Total time taken: 1m31.7646708s
> constants.go:1: running "stringer": exec: "stringer": executable file not found in %PATH%

Fixed it with:

> go get golang.org/x/tools/cmd/stringer

Maybe add as dependency somewhere or in readme

**Comment by F21** [comment]
Thanks for reporting!
