### ISSUE TITLE
PostCodeRegex Doesn't Require Exact Match to Pass Validation.

### ISSUE THREAD

**Issue by JackIngleton** [Boostport/address#23]
`regexp.MatchString` used in `checkPostCode` returns `true` as long as the test address contains a match, but doesn't enforce an exact match.

This is causing issues for us where users are entering in extra information into the address form. E.G. ` NSW 3500` is accepted as a valid post code for Australia NSW, whereas the correct post code is `3500`. 

A simple fix for this might be to wrap the top-level regex with `^()$`. E.g. `\d{4}` would become `^(\d{4})$`.

**Comment by F21** [comment]
Thanks for reporting this! This has been fixed in `v0.6.0`.

**Comment by JackIngleton** [comment]
@F21 Thank you for resolving this so quickly! This will be really useful for us.
